// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bancontinental.Models;

namespace bancontinental.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20211206125421_migracion1")]
    partial class migracion1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("bancontinental.Models.Banco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("bancos");
                });

            modelBuilder.Entity("bancontinental.Models.BancoCuenta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("idBanco")
                        .HasColumnType("int");

                    b.Property<int>("nroCuenta")
                        .HasColumnType("int");

                    b.Property<int>("saldo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("bancosCuentas");
                });

            modelBuilder.Entity("bancontinental.Models.BancoCuentaTrnsaccion", b =>
                {
                    b.Property<int>("idNroTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("envio")
                        .HasColumnType("bit");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idBancoDestino")
                        .HasColumnType("int");

                    b.Property<int>("idBancoOrigen")
                        .HasColumnType("int");

                    b.Property<int>("monto")
                        .HasColumnType("int");

                    b.Property<int>("nroCuentaDestino")
                        .HasColumnType("int");

                    b.Property<int>("nroCuentaOrigen")
                        .HasColumnType("int");

                    b.HasKey("idNroTransaccion");

                    b.ToTable("bancosCuentasTransacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
